[tool.poetry]
name = "alpaca-pyspark"
version = "0.1.0"
description = "Import market data from Alpaca-API with PySpark"
authors = ["Tristan Nixon <tristan.nixon@example.com>"]
readme = "README.md"
packages = [{include = "alpaca_pyspark"}]
license = "LICENSE"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.0"
requests = "^2.31.0"
pyspark = "^4.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.0.0"
flake8 = "^6.0.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"